= stepmod-utils Ruby gem

image:https://img.shields.io/gem/v/metanorma.svg["Gem Version", link="https://rubygems.org/gems/metanorma"]
image:https://github.com/metanorma/stepmod-utils/workflows/ubuntu/badge.svg["Ubuntu Build Status", link="https://github.com/metanorma/stepmod-utils/actions?query=workflow%3Aubuntu"]
image:https://github.com/metanorma/stepmod-utils/workflows/macos/badge.svg["OSX Build Status", link="https://github.com/metanorma/stepmod-utils/actions?query=workflow%3Amacos"]
image:https://github.com/metanorma/stepmod-utils/workflows/windows/badge.svg["Windows Build Status", link="https://github.com/metanorma/stepmod-utils/actions?query=workflow%3Awindows"]
image:https://codeclimate.com/github/metanorma/stepmod-utils/badges/gpa.svg["Code Climate", link="https://codeclimate.com/github/metanorma/stepmod-utils"]
image:https://img.shields.io/github/issues-pr-raw/metanorma/stepmod-utils.svg["Pull Requests", link="https://github.com/metanorma/stepmod-utils/pulls"]
image:https://img.shields.io/github/commits-since/metanorma/stepmod-utils/latest.svg["Commits since latest",link="https://github.com/metanorma/stepmod-utils/releases"]

== Purpose

The `stepmod-utils` Ruby gem provides a number of tools to work with the STEPmod repository.

== Installation

[source,ruby]
----
gem install stepmod-utils
----

Or include it in your gemspec.

== Usage

[source,sh]
----
# Extracts from current directory
$ stepmod-extract-terms

# Extracts from specified stepmod/ or stepmod/data/ directory
$ stepmod-extract-terms {stepmod-data-directory}
----

Then these files will be created:

* `031-generated-terms.adoc` all terms extracted
* `991-generated-bibliography.adoc` all bibliographic sources where the terms come from


== CVS revision detection

If the STEPmod repository is a CVS repository, it will display the
working and repository revisions as comments.

WARNING: CVS revision detection can be *slow*! Be patient.

Sample output:

[source,sh]
----
[stepmod-utils] INFO: STEPmod directory set to ../x/stepmod/.
[stepmod-utils] INFO: STEPmod directory is a CVS repository and will detect revisions.
[stepmod-utils] INFO: [CVS] Detecting file revisions can be slow, please be patient!
[stepmod-utils] INFO: Detecting paths...
[stepmod-utils] INFO: Processing XML file data/business_object_models/managed_model_based_3d_engineering/business_object_model.xml
[stepmod-utils] INFO: Detecting CVS revision...
[stepmod-utils] INFO: CVS working rev (1.148), repo rev (1.148)
[stepmod-utils] INFO: Completed processing XML file data/business_object_models/managed_model_based_3d_engineering/business_object_model.xml
[stepmod-utils] INFO: Processing XML file data/business_object_models/managed_model_based_3d_engineering_domain/business_object_model.xml
[stepmod-utils] INFO: Detecting CVS revision...
[stepmod-utils] INFO: CVS working rev (1.31), repo rev (1.31)
[stepmod-utils] INFO: Completed processing XML file data/business_object_models/managed_model_based_3d_engineering_domain/business_object_model.xml
...
 stepmod/data/business_object_models/managed_model_based_3d_engineering_domain/business_object_model.xml
[stepmod-utils] INFO: written to: 031-generated-terms.adoc
[stepmod-utils] INFO: written to: 991-generated-bibliography.adoc
----


== Non-CVS repository

If the STEPmod repository is not a CVS repository, or if the `cvs` executable
cannot be found, term extract will still work.

Sample output:

[source,sh]
----
[stepmod-utils] INFO: STEPmod directory set to ../iso-10303-stepmod.
[stepmod-utils] INFO: STEPmod directory is not a CVS repository, skipping revision detection.
[stepmod-utils] INFO: Detecting paths...
[stepmod-utils] INFO: Processing XML file data/application_protocols/boundary_representation_for_iso_14306_open_jt/application_protocol.xml
[stepmod-utils] INFO: skipped ISO/CD 10303-243 as it is not IS, DIS or TS
[stepmod-utils] INFO: Processing XML file data/application_protocols/configuration_control_3d_design_ed2/application_protocol.xml
[stepmod-utils] INFO: Completed processing XML file data/application_protocols/configuration_control_3d_design_ed2/application_protocol.xml
[stepmod-utils] INFO: Processing XML file data/application_protocols/electronic_assembly_interconnect_and_packaging_design/application_protocol.xml
[stepmod-utils] INFO: skipped ISO/CD 10303-210:2019 as it is not IS, DIS or TS
[stepmod-utils] INFO: Processing XML file data/application_protocols/functional_data_and_their_schematic_representation_for_process_plant/application_protocol.xml
[stepmod-utils] INFO: Completed processing XML file data/application_protocols/functional_data_and_their_schematic_representation_for_process_plant/application_protocol.xml
...
----

