name: generate_yaml_concepts

on:
  push:
    branches: [ main ]

jobs:
  generate_yaml_concepts:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Git
        run: |
          git config --global init.defaultBranch main
          git config --global user.name "stepmod-utils-ci"
          git config --global user.email "stepmod-utils-ci@users.noreply.github.com"

      - name: Install required gems
        run: |-
          sudo gem install stepmod-utils
          sudo gem install pry

      - name: Check out iso-10303-stepmod-wg12 repo
        uses: actions/checkout@v3
        with:
          repository: metanorma/iso-10303-stepmod-wg12
          token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}
          path: iso-10303-stepmod-wg12

      - name: Generate annotated express files
        run: stepmod-annotate-all ./iso-10303-stepmod-wg12

      - name: Remove old directory for `yaml` files
        working-directory: iso-10303-stepmod-wg12
        run: rm -rf output-yaml

      - name: Make directory for `yaml` files
        working-directory: iso-10303-stepmod-wg12
        run: mkdir output-yaml

      - name: Generate `yaml` concepts
        working-directory: iso-10303-stepmod-wg12/output-yaml
        run: |
          stepmod-extract-yaml-terms \
            -p ../data \
            -i ../repository_index.xml

      - name: Skip push to iso-10303-stepmod-wg12 if no changes
        id: git_status
        working-directory: iso-10303-stepmod-wg12
        run: |
          echo "STATUS=$(git status --porcelain | tr -d [:space:])" >> $GITHUB_OUTPUT

      - name: Commit `yaml` files to iso-10303-stepmod-wg12
        if: steps.git_status.outputs.STATUS != ''
        working-directory: iso-10303-stepmod-wg12
        run: |
          git add output-yaml/*.yaml
          git commit -m 'Update yaml concept files'

      - name: Push `yaml` files to iso-10303-stepmod-wg12
        if: steps.git_status.outputs.STATUS != ''
        working-directory: iso-10303-stepmod-wg12
        run: |
          git push origin main
