name: release-tag

on:
  workflow_dispatch:
    inputs:
      next_version:
        description: |
          Possible values:
           - 1.1.1       # Bump to the given, specific version number
           - major       # Bump to the next major level (e.g. 0.0.1 to 1.0.0)
           - minor       # Bump to the next minor level (e.g. 0.0.1 to 0.1.0)
           - patch       # Bump to the next patch level (e.g. 0.0.1 to 0.0.2)
           - pre|rc|etc  # Bump to the next pre-release level (e.g. 0.0.1 to 0.1.0.pre.1, 1.0.0.pre.1 to 1.0.0.pre.2)
        required: true
        default: 'patch'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - run: |
          gem install gem-release    

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          gem bump --version ${{ github.event.inputs.next_version }} --tag --push
