name: release-tag

on:
  workflow_dispatch:
    inputs:
      next_version:
        description: |
          Possible values: x.y.z, major, minor, patch or pre|rc|etc
        required: true
        default: 'patch'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - run: |
          gem install gem-release    

      - run: |
          git config user.name "metanorma-ci" # github-actions will not trigger other workflows
          git config user.email "metanorma-ci@users.noreply.github.com"
          git remote add github "https://metanorma-ci:${{ secrets.METANORMA_CI_PAT_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git pull github ${GITHUB_REF} --ff-only
          gem bump --version ${{ github.event.inputs.next_version }} --tag --push
